from django.urls import path

from webroaster.views.human_resource import pages
from webroaster.views.human_resource import views


urlpatterns = [
    path("employees/", views.employee_list_create, name="employee-list-create"),
    path("employees/<int:pk>/", views.employee_detail, name="employee-detail"),
    path("guards/", views.guard_list_create, name="guard-list-create"),
    path("guards/<int:pk>/", views.guard_detail, name="guard-detail"),
    path("supervisors/", views.supervisor_list_create, name="supervisor-list-create"),
    path("supervisors/<int:pk>/", views.supervisor_detail, name="supervisor-detail"),
    path("trainings/", views.training_list_create, name="training-list-create"),
    path("trainings/<int:pk>/", views.training_detail, name="training-detail"),
    path("attendance/", views.attendance_list_create, name="attendance-list-create"),
    path("attendance/<int:pk>/", views.attendance_detail, name="attendance-detail"),
    path("leaves/", views.leave_list_create, name="leave-list-create"),
    path("leaves/<int:pk>/", views.leave_detail, name="leave-detail"),
    path("disciplinary-actions/", views.disciplinary_action_list_create, name="disciplinary-action-list-create"),
    path("disciplinary-actions/<int:pk>/", views.disciplinary_action_detail, name="disciplinary-action-detail"),
    path("performance-evaluations/", views.performance_evaluation_list_create, name="performance-evaluation-list-create"),
    path("performance-evaluations/<int:pk>/", views.performance_evaluation_detail, name="performance-evaluation-detail"),
    path("documents/", views.document_list_create, name="document-list-create"),
    path("documents/<int:pk>/", views.document_detail, name="document-detail"),
    path("pages/employees/", pages.employee_page_list, name="hr-employee-page-list"),
    path("pages/employees/create/", pages.employee_page_create, name="hr-employee-page-create"),
    path("pages/employees/<int:pk>/", pages.employee_page_detail, name="hr-employee-page-detail"),
    path("pages/employees/<int:pk>/edit/", pages.employee_page_update, name="hr-employee-page-update"),
    path("pages/employees/<int:pk>/delete/", pages.employee_page_delete, name="hr-employee-page-delete"),
    path("pages/guards/", pages.guard_page_list, name="hr-guard-page-list"),
    path("pages/guards/create/", pages.guard_page_create, name="hr-guard-page-create"),
    path("pages/guards/<int:pk>/", pages.guard_page_detail, name="hr-guard-page-detail"),
    path("pages/guards/<int:pk>/edit/", pages.guard_page_update, name="hr-guard-page-update"),
    path("pages/guards/<int:pk>/delete/", pages.guard_page_delete, name="hr-guard-page-delete"),
    path("pages/supervisors/", pages.supervisor_page_list, name="hr-supervisor-page-list"),
    path("pages/supervisors/create/", pages.supervisor_page_create, name="hr-supervisor-page-create"),
    path("pages/supervisors/<int:pk>/", pages.supervisor_page_detail, name="hr-supervisor-page-detail"),
    path("pages/supervisors/<int:pk>/edit/", pages.supervisor_page_update, name="hr-supervisor-page-update"),
    path("pages/supervisors/<int:pk>/delete/", pages.supervisor_page_delete, name="hr-supervisor-page-delete"),
    path("pages/trainings/", pages.training_page_list, name="hr-training-page-list"),
    path("pages/trainings/create/", pages.training_page_create, name="hr-training-page-create"),
    path("pages/trainings/<int:pk>/", pages.training_page_detail, name="hr-training-page-detail"),
    path("pages/trainings/<int:pk>/edit/", pages.training_page_update, name="hr-training-page-update"),
    path("pages/trainings/<int:pk>/delete/", pages.training_page_delete, name="hr-training-page-delete"),
    path("pages/attendance/", pages.attendance_page_list, name="hr-attendance-page-list"),
    path("pages/attendance/create/", pages.attendance_page_create, name="hr-attendance-page-create"),
    path("pages/attendance/<int:pk>/", pages.attendance_page_detail, name="hr-attendance-page-detail"),
    path("pages/attendance/<int:pk>/edit/", pages.attendance_page_update, name="hr-attendance-page-update"),
    path("pages/attendance/<int:pk>/delete/", pages.attendance_page_delete, name="hr-attendance-page-delete"),
    path("pages/leaves/", pages.leave_page_list, name="hr-leave-page-list"),
    path("pages/leaves/create/", pages.leave_page_create, name="hr-leave-page-create"),
    path("pages/leaves/<int:pk>/", pages.leave_page_detail, name="hr-leave-page-detail"),
    path("pages/leaves/<int:pk>/edit/", pages.leave_page_update, name="hr-leave-page-update"),
    path("pages/leaves/<int:pk>/delete/", pages.leave_page_delete, name="hr-leave-page-delete"),
    path("pages/disciplinary-actions/", pages.disciplinary_action_page_list, name="hr-disciplinary-action-page-list"),
    path("pages/disciplinary-actions/create/", pages.disciplinary_action_page_create, name="hr-disciplinary-action-page-create"),
    path("pages/disciplinary-actions/<int:pk>/", pages.disciplinary_action_page_detail, name="hr-disciplinary-action-page-detail"),
    path("pages/disciplinary-actions/<int:pk>/edit/", pages.disciplinary_action_page_update, name="hr-disciplinary-action-page-update"),
    path("pages/disciplinary-actions/<int:pk>/delete/", pages.disciplinary_action_page_delete, name="hr-disciplinary-action-page-delete"),
    path("pages/performance-evaluations/", pages.performance_evaluation_page_list, name="hr-performance-evaluation-page-list"),
    path("pages/performance-evaluations/create/", pages.performance_evaluation_page_create, name="hr-performance-evaluation-page-create"),
    path("pages/performance-evaluations/<int:pk>/", pages.performance_evaluation_page_detail, name="hr-performance-evaluation-page-detail"),
    path("pages/performance-evaluations/<int:pk>/edit/", pages.performance_evaluation_page_update, name="hr-performance-evaluation-page-update"),
    path("pages/performance-evaluations/<int:pk>/delete/", pages.performance_evaluation_page_delete, name="hr-performance-evaluation-page-delete"),
    path("pages/documents/", pages.document_page_list, name="hr-document-page-list"),
    path("pages/documents/create/", pages.document_page_create, name="hr-document-page-create"),
    path("pages/documents/<int:pk>/", pages.document_page_detail, name="hr-document-page-detail"),
    path("pages/documents/<int:pk>/edit/", pages.document_page_update, name="hr-document-page-update"),
    path("pages/documents/<int:pk>/delete/", pages.document_page_delete, name="hr-document-page-delete"),
]

