# Generated by Django 6.0.7 on 2026-07-14 07:01

import django.db.models.deletion
from django.db import migrations, models


LEGACY_TABLE_RENAMES = (
    ("webroaster_client", "clients"),
    ("webroaster_employee", "employees"),
    ("webroaster_invoice", "invoices"),
    ("webroaster_budget", "budgets"),
    ("webroaster_guard", "guards"),
    ("webroaster_document", "documents"),
    ("webroaster_disciplinaryaction", "disciplinary_actions"),
    ("webroaster_attendance", "attendance"),
    ("webroaster_advance", "advances"),
    ("webroaster_expense", "expenses"),
    ("webroaster_leave", "leaves"),
    ("webroaster_payment", "payments"),
    ("webroaster_performanceevaluation", "performance_evaluations"),
    ("webroaster_salary", "salaries"),
    ("webroaster_site", "sites"),
    ("webroaster_shift", "shifts"),
    ("webroaster_patrollog", "patrol_logs"),
    ("webroaster_incident", "incidents"),
    ("webroaster_deployment", "deployments"),
    ("webroaster_asset", "assets"),
    ("webroaster_supervisor", "supervisors"),
    ("webroaster_training", "training"),
)

LEGACY_PRIMARY_KEY_RENAMES = (
    ("clients", "client_id"),
    ("employees", "employee_id"),
    ("invoices", "invoice_id"),
    ("budgets", "budget_id"),
    ("documents", "doc_id"),
    ("disciplinary_actions", "action_id"),
    ("attendance", "attendance_id"),
    ("advances", "advance_id"),
    ("expenses", "expense_id"),
    ("leaves", "leave_id"),
    ("payments", "payment_id"),
    ("performance_evaluations", "eval_id"),
    ("salaries", "salary_id"),
    ("sites", "site_id"),
    ("shifts", "shift_id"),
    ("patrol_logs", "patrol_id"),
    ("incidents", "incident_id"),
    ("deployments", "deployment_id"),
    ("assets", "asset_id"),
    ("supervisors", "supervisor_id"),
    ("training", "training_id"),
)


def rename_legacy_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.quote_name

    for old_name, new_name in LEGACY_TABLE_RENAMES:
        if old_name in existing_tables and new_name not in existing_tables:
            schema_editor.execute(f"ALTER TABLE {quote_name(old_name)} RENAME TO {quote_name(new_name)}")
            existing_tables.remove(old_name)
            existing_tables.add(new_name)

    with schema_editor.connection.cursor() as cursor:
        for table_name, new_column_name in LEGACY_PRIMARY_KEY_RENAMES:
            if table_name not in existing_tables:
                continue
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = %s AND column_name = 'id'
                """,
                [table_name],
            )
            has_legacy_id = cursor.fetchone()
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table_name, new_column_name],
            )
            has_new_id = cursor.fetchone()
            if has_legacy_id and not has_new_id:
                schema_editor.execute(
                    f"ALTER TABLE {quote_name(table_name)} RENAME COLUMN {quote_name('id')} TO {quote_name(new_column_name)}"
                )

        for _old_name, table_name in LEGACY_TABLE_RENAMES:
            if table_name not in existing_tables:
                continue
            for column_name in ("created_at", "updated_at"):
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = %s AND column_name = %s
                    """,
                    [table_name, column_name],
                )
                if not cursor.fetchone():
                    schema_editor.execute(
                        f"ALTER TABLE {quote_name(table_name)} "
                        f"ADD COLUMN {quote_name(column_name)} timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP"
                    )


def rename_legacy_tables_reverse(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    quote_name = schema_editor.quote_name

    for old_name, new_name in reversed(LEGACY_TABLE_RENAMES):
        if new_name in existing_tables and old_name not in existing_tables:
            schema_editor.execute(f"ALTER TABLE {quote_name(new_name)} RENAME TO {quote_name(old_name)}")
            existing_tables.remove(new_name)
            existing_tables.add(old_name)


def copy_client_contracts(apps, schema_editor):
    Client = apps.get_model('webroaster', 'Client')
    Contract = apps.get_model('webroaster', 'Contract')

    contracts = []
    for client in Client.objects.all():
        contracts.append(
            Contract(
                client_id=client.client_id,
                contract_start_date=client.contract_start_date,
                contract_end_date=client.contract_end_date,
                contract_status=client.contract_status,
                created_at=client.created_at,
                updated_at=client.updated_at,
            )
        )

    Contract.objects.bulk_create(contracts)


def restore_client_contracts(apps, schema_editor):
    Client = apps.get_model('webroaster', 'Client')
    Contract = apps.get_model('webroaster', 'Contract')

    for client in Client.objects.all():
        contract = Contract.objects.filter(client_id=client.client_id).order_by('contract_start_date').first()
        if contract:
            client.contract_start_date = contract.contract_start_date
            client.contract_end_date = contract.contract_end_date
            client.contract_status = contract.contract_status
            client.save(update_fields=['contract_start_date', 'contract_end_date', 'contract_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_legacy_tables, rename_legacy_tables_reverse),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='webroaster.client')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.RunPython(copy_client_contracts, restore_client_contracts),
        migrations.RemoveField(
            model_name='client',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_status',
        ),
    ]

