# Generated by Django 6.0.7 on 2026-07-14 10:06

from django.db import migrations, models


def recalculate_shift_types(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE shifts
            SET shift_type = CASE
                WHEN EXTRACT(HOUR FROM start_time) >= 7 AND EXTRACT(HOUR FROM start_time) < 18 THEN 'day'
                ELSE 'night'
            END
            WHERE start_time IS NOT NULL
            """
        )

class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0010_site_activity_site_day_shift_guards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='description',
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], editable=False, max_length=20),
        ),
        migrations.RunPython(recalculate_shift_types, migrations.RunPython.noop),
    ]


