# Generated by Django 6.0.7 on 2026-07-14 10:17

import django.db.models.deletion
from django.db import migrations, models


def ensure_shift_site_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'shifts' AND column_name = 'site_id'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE shifts ADD COLUMN site_id bigint NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0011_remove_shift_description_alter_shift_shift_type'),
    ]

    operations = [
        migrations.RunPython(ensure_shift_site_column, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shift',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='webroaster.site'),
        ),
    ]

