# Generated by Django 6.0.7 on 2026-07-14 13:47

from django.db import migrations, models


def ensure_shift_date_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'shifts' AND column_name = 'shift_date'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE shifts ADD COLUMN shift_date date NULL")


def collapse_daily_shifts(apps, schema_editor):
    Shift = apps.get_model('webroaster', 'Shift')
    Deployment = apps.get_model('webroaster', 'Deployment')
    Attendance = apps.get_model('webroaster', 'Attendance')

    canonical_by_template = {}
    for shift in Shift.objects.order_by('shift_id'):
        shift.shift_type = 'day' if 7 <= shift.start_time.hour < 18 else 'night'
        shift.save(update_fields=['shift_type'])

        key = (shift.start_time, shift.end_time, shift.hours_per_shift)
        canonical = canonical_by_template.get(key)
        if canonical is None:
            canonical_by_template[key] = shift
            continue

        Deployment.objects.filter(shift=shift).update(shift=canonical)
        Attendance.objects.filter(shift=shift).update(shift=canonical)
        shift.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0014_attendance_attended_guard_attendance_deployment_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_shift_date_column, migrations.RunPython.noop),
        migrations.RunPython(collapse_daily_shifts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='shift',
            name='shift_date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='site',
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time', 'hours_per_shift'), name='unique_shift_template'),
        ),
    ]

