# Generated by Django 6.0.7 on 2026-07-14 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def ensure_asset_site_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'assets' AND column_name = 'site_id'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE assets ADD COLUMN site_id bigint NULL")


def preserve_existing_asset_sites(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'assets'
            """
        )
        columns = {row[0] for row in cursor.fetchall()}
        if not {'asset_id', 'site_id'}.issubset(columns):
            return
        quantity_expression = 'quantity' if 'quantity' in columns else '1'
        schema_editor.execute(
            f"""
            INSERT INTO asset_assignments (asset_id, site_id, quantity, status, notes, assigned_date, created_at, updated_at)
            SELECT asset_id, site_id, {quantity_expression}, 'assigned', 'Created from previous asset site assignment.',
                   CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM assets
            WHERE site_id IS NOT NULL
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0016_remove_site_activity_remove_site_rate_per_guard_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_asset_site_column, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('uniform', 'Uniform'), ('gun', 'Gun'), ('weapon', 'Weapon'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='webroaster.asset')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webroaster.deployment')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='webroaster.employee')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webroaster.guard')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webroaster.site')),
            ],
            options={
                'db_table': 'asset_assignments',
            },
        ),
        migrations.RunPython(preserve_existing_asset_sites, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='asset',
            name='site',
        ),
    ]

