# Generated by Django 6.0.7 on 2026-07-14 15:06

from django.db import migrations, models


def ensure_asset_number_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'assets' AND column_name = 'asset_number'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE assets ADD COLUMN asset_number varchar(100) NOT NULL DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0017_remove_asset_site_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='asset',
                    name='asset_name',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(ensure_asset_number_column, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial Number'),
        ),
    ]

