# Generated by Django 6.0.7 on 2026-07-15 11:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def ensure_employee_role_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'employees' AND column_name = 'role_id'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE employees ADD COLUMN role_id bigint NULL")


def employee_columns(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'employees'
            """
        )
        return {row[0] for row in cursor.fetchall()}


def ensure_employee_department_column(apps, schema_editor):
    if "department" not in employee_columns(schema_editor):
        schema_editor.execute(
            "ALTER TABLE employees ADD COLUMN department varchar(50) NOT NULL DEFAULT 'operations'"
        )


def backfill_employee_roles(apps, schema_editor):
    columns = employee_columns(schema_editor)
    role_source = "role_name" if "role_name" in columns else "role"
    position_source = "position_title" if "position_title" in columns else role_source
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE employees
            SET
                role = CASE
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%guard%' THEN 'guard'
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%supervisor%' THEN 'supervisor'
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%hr%' THEN 'hr_officer'
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%finance%' THEN 'finance_officer'
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%admin%' THEN 'administrator'
                    WHEN lower(coalesce({role_source}::text, '')) LIKE '%manager%' THEN 'manager'
                    ELSE 'operations_officer'
                END,
                position = CASE
                    WHEN lower(coalesce({position_source}::text, {role_source}::text, '')) LIKE '%supervisor%' THEN 'site_supervisor'
                    WHEN lower(coalesce({position_source}::text, {role_source}::text, '')) LIKE '%hr%' THEN 'hr_officer'
                    WHEN lower(coalesce({position_source}::text, {role_source}::text, '')) LIKE '%finance%' THEN 'finance_officer'
                    WHEN lower(coalesce({position_source}::text, {role_source}::text, '')) LIKE '%admin%' THEN 'administrator'
                    WHEN lower(coalesce({position_source}::text, {role_source}::text, '')) LIKE '%manager%' THEN 'operations_officer'
                    ELSE 'security_guard'
                END,
                department = CASE
                    WHEN lower(coalesce(department::text, {role_source}::text, '')) LIKE '%hr%' THEN 'hr'
                    WHEN lower(coalesce(department::text, {role_source}::text, '')) LIKE '%finance%' THEN 'finance'
                    WHEN lower(coalesce(department::text, {role_source}::text, '')) LIKE '%admin%' THEN 'admin'
                    ELSE 'operations'
                END
            """
        )
        cursor.execute(
            """
            UPDATE employees
            SET salary_scale = CASE position
                WHEN 'site_supervisor' THEN 900000.00
                WHEN 'regional_supervisor' THEN 1200000.00
                WHEN 'operations_officer' THEN 1100000.00
                WHEN 'hr_officer' THEN 1000000.00
                WHEN 'finance_officer' THEN 1000000.00
                WHEN 'administrator' THEN 950000.00
                ELSE 650000.00
            END
            """
        )
        cursor.execute(
            """
            UPDATE salaries
            SET basic_salary = employees.salary_scale
            FROM employees
            WHERE salaries.employee_id = employees.employee_id
              AND employees.salary_scale IS NOT NULL
            """
        )

class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0021_employee_nssf_number'),
    ]

    operations = [
        migrations.RunPython(ensure_employee_role_column, migrations.RunPython.noop),
        migrations.RunPython(ensure_employee_department_column, migrations.RunPython.noop),
        migrations.AddField(
            model_name='employee',
            name='armed_status',
            field=models.CharField(blank=True, choices=[('armed', 'Armed'), ('unarmed', 'Unarmed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='authority_level',
            field=models.CharField(blank=True, choices=[('site', 'Site Level'), ('regional', 'Regional Level'), ('national', 'National Level')], default='', max_length=50),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='employee',
                    name='department',
                    field=models.CharField(choices=[('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('admin', 'Administration')], default='operations', max_length=50),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('security_guard', 'Security Guard'), ('site_supervisor', 'Site Supervisor'), ('regional_supervisor', 'Regional Supervisor'), ('operations_officer', 'Operations Officer'), ('hr_officer', 'HR Officer'), ('finance_officer', 'Finance Officer'), ('administrator', 'Administrator')], default='security_guard', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Security'), ('advanced', 'Advanced Security'), ('specialized', 'Specialized Training')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_scale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_asset_assignments', to='webroaster.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_attendance_records', to='webroaster.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scheduled_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_attendance_records', to='webroaster.employee'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_deployments', to='webroaster.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('guard', 'Guard'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('operations_officer', 'Operations Officer'), ('hr_officer', 'HR Officer'), ('finance_officer', 'Finance Officer'), ('administrator', 'Administrator')], default='guard', max_length=50),
        ),
        migrations.RunPython(backfill_employee_roles, migrations.RunPython.noop),
    ]

