# Generated by Django 6.0.7 on 2026-07-17 16:08

import django.db.models.deletion
from django.db import migrations, models


def table_columns(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
            """,
            [table_name],
        )
        return {row[0] for row in cursor.fetchall()}


def ensure_deployment_columns(apps, schema_editor):
    columns = table_columns(schema_editor, "deployments")
    if "client_id" not in columns:
        schema_editor.execute("ALTER TABLE deployments ADD COLUMN client_id bigint NULL")
    if "guard_id" not in columns:
        schema_editor.execute("ALTER TABLE deployments ADD COLUMN guard_id bigint NULL")


def copy_deployment_data(apps, schema_editor):
    through_table = "webroaster_site_guards"
    through_columns = table_columns(schema_editor, through_table)
    has_through_table = {"site_id", "employee_id"}.issubset(through_columns)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE deployments
            SET client_id = sites.client_id
            FROM sites
            WHERE deployments.site_id = sites.site_id
              AND deployments.site_id IS NOT NULL
              AND deployments.client_id IS NULL
            """
        )
        if has_through_table:
            cursor.execute(
                f"""
                INSERT INTO {through_table} (site_id, employee_id)
                SELECT DISTINCT site_id, guard_id
                FROM deployments
                WHERE site_id IS NOT NULL AND guard_id IS NOT NULL
                ON CONFLICT DO NOTHING
                """
            )


def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0022_employee_armed_status_employee_authority_level_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_deployment_columns, noop_reverse),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='deployment',
                    name='client',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='webroaster.client'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='site',
            name='guards',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to='webroaster.employee'),
        ),
        migrations.RunPython(copy_deployment_data, noop_reverse),
    ]


