# Generated by Django 6.0.7 on 2026-07-20 22:36

import django.db.models.deletion
from django.db import migrations, models


def ensure_paymees_table(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if "paymees" in existing_tables:
        return
    schema_editor.execute(
        """
        CREATE TABLE paymees (
            invoice_id bigint PRIMARY KEY REFERENCES invoices(invoice_id) DEFERRABLE INITIALLY DEFERRED,
            total_amount numeric(12, 2) NOT NULL DEFAULT 0,
            amount_paid numeric(12, 2) NOT NULL DEFAULT 0,
            status varchar(20) NOT NULL DEFAULT 'pending',
            created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0047_update_supervisor_employee_numbers'),
    ]

    operations = [
        migrations.RunPython(ensure_paymees_table, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='paymee',
            options={'verbose_name': 'Receivable', 'verbose_name_plural': 'Receivables'},
        ),
        migrations.AddField(
            model_name='paymee',
            name='client',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='webroaster.client'),
        ),
        migrations.AddField(
            model_name='paymee',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddField(
            model_name='paymee',
            name='due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymee',
            name='last_payment_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymee',
            name='payment_terms',
            field=models.CharField(default='Due on receipt', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('overpaid', 'Overpaid'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]

