# Generated by Django 6.0.7 on 2026-07-20 23:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def seed_existing_expense_requisitions(apps, schema_editor):
    schema_editor.execute(
        """
        UPDATE expenses
        SET
            expense_code = COALESCE(
                expense_code,
                'EXP-' || COALESCE(EXTRACT(YEAR FROM expense_date)::int, 2026)::text || '-' || lpad(expense_id::text, 5, '0')
            ),
            requisition_title = CASE
                WHEN requisition_title IS NULL OR requisition_title = 'Expense Requisition'
                THEN category || ' Expense ' || expense_id::text
                ELSE requisition_title
            END,
            requested_amount = CASE
                WHEN requested_amount = 0 THEN amount
                ELSE requested_amount
            END,
            accountability_status = CASE
                WHEN amount > 0 AND accountability_status = 'not_due' THEN 'submitted'
                ELSE accountability_status
            END
        """
    )


def reverse_seed_existing_expense_requisitions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0050_budget_accountability_status_budget_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accountability_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='accountability_status',
            field=models.CharField(choices=[('not_due', 'Not Due'), ('pending_accountability', 'Pending Accountability'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='not_due', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='accounted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='expense',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_requisitions_requested', to='webroaster.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='requisition_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='requisition_title',
            field=models.CharField(default='Expense Requisition', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_payee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('requisition', 'Requisition'), ('recorded', 'Recorded'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requisition', max_length=20),
        ),
        migrations.RunPython(seed_existing_expense_requisitions, reverse_seed_existing_expense_requisitions),
        migrations.CreateModel(
            name='ExpenseNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_group', models.CharField(max_length=50)),
                ('notification_type', models.CharField(choices=[('missing_accountability', 'Missing Expense Accountability')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webroaster.expense')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_notifications', to='webroaster.employee')),
            ],
            options={
                'db_table': 'expense_notifications',
                'constraints': [models.UniqueConstraint(fields=('expense', 'recipient', 'notification_type'), name='unique_expense_notification_per_recipient')],
            },
        ),
    ]


