# Generated by Django 6.0.7 on 2026-07-23 17:24

from django.db import migrations, models


def ensure_invoice_number_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'invoices' AND column_name = 'invoice_number'
            """
        )
        if not cursor.fetchone():
            schema_editor.execute("ALTER TABLE invoices ADD COLUMN invoice_number varchar(20) NULL")


def backfill_invoice_numbers(apps, schema_editor):
    schema_editor.execute(
        """
        UPDATE invoices
        SET invoice_number = 'INV' || lpad(invoice_id::text, 3, '0')
        WHERE invoice_number IS NULL OR invoice_number = ''
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0055_payrolldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billable_products',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='webroaster.contractdeliverable'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='invoice',
                    name='invoice_number',
                    field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(ensure_invoice_number_column, migrations.RunPython.noop),
        migrations.RunPython(backfill_invoice_numbers, migrations.RunPython.noop),
    ]

