# Generated by Django 6.0.7 on 2026-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0085_employee_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='provider',
            field=models.CharField(default='NewCompany', max_length=255),
        ),
    ]
