# Generated by Django 6.0.7 on 2026-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0088_relax_deployment_guard_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='day_guards',
            field=models.ManyToManyField(blank=True, related_name='day_shift_deployments', to='webroaster.employee'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='night_guards',
            field=models.ManyToManyField(blank=True, related_name='night_shift_deployments', to='webroaster.employee'),
        ),
    ]
