# Generated by Django 6.0.7 on 2026-09-18 10:57

from django.db import migrations, models


def fill_empty_remarks(apps, schema_editor):
    Attendance = apps.get_model("webroaster", "Attendance")
    Attendance.objects.filter(remarks__isnull=True).update(remarks="")


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0089_deployment_day_guards_deployment_night_guards'),
    ]

    operations = [
        migrations.RunPython(fill_empty_remarks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
