# Generated by Django 6.0.7 on 2026-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webroaster', '0095_repair_invoice_total_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'site', 'shift'], name='att_date_site_shift_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='att_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['scheduled_guard', 'date'], name='att_scheduled_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['deployment', 'date'], name='att_deployment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['site', 'status', 'start_date'], name='dep_site_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['site', 'status', 'end_date'], name='dep_site_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['shift_coverage', 'status'], name='dep_coverage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentarea',
            index=models.Index(fields=['region', 'status', 'start_date'], name='deparea_region_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentarea',
            index=models.Index(fields=['employee', 'status', 'start_date'], name='deparea_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentarea',
            index=models.Index(fields=['region', 'end_date'], name='deparea_region_end_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'role', 'employee_number'], name='emp_status_role_num_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='emp_department_status_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['region', 'site_name'], name='site_region_name_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['contract', 'site_name'], name='site_contract_name_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['client', 'site_name'], name='site_client_name_idx'),
        ),
    ]
