"""
Django settings for NewCompany project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    return default


def env_list(name, default=""):
    return [value.strip() for value in os.environ.get(name, default).split(",") if value.strip()]


def first_env_value(*names):
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return None


PLACEHOLDER_DATABASE_HOSTS = {"host", "hostname", "example.com", "localhost.localdomain"}


def clean_database_url(value):
    value = value.strip().strip("'\"")
    match = re.search(r"(?:postgres|postgresql)://[^\s'\"]+", value)
    if match:
        value = match.group(0)
    return value


def is_usable_database_url(value):
    parsed = urlparse(value)
    return parsed.scheme in {"postgres", "postgresql"} and parsed.hostname not in PLACEHOLDER_DATABASE_HOSTS


def first_database_url(*names):
    for name in names:
        value = os.environ.get(name)
        if not value:
            continue
        value = clean_database_url(value)
        if "://" not in value and os.environ.get(value):
            value = clean_database_url(os.environ[value])
        if value and is_usable_database_url(value):
            return value
    return None


def database_url_requires_ssl(database_url):
    parsed = urlparse(database_url)
    if parsed.hostname in {"127.0.0.1", "localhost"}:
        return False
    if "sslmode=" in parsed.query:
        return False
    return True


def fallback_database_config():
    if DEBUG:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "NewCompany"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("LOCAL_DB_PASSWORD") or os.environ.get("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_FALLBACK_PATH", "/tmp/newcompany-config-error.sqlite3"),
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
IS_VERCEL_RUNTIME = bool(os.environ.get("VERCEL") or os.environ.get("VERCEL_ENV"))
DEBUG = env_bool("DJANGO_DEBUG", env_bool("DEBUG", not IS_VERCEL_RUNTIME))
SECRET_KEY = os.environ.get("SECRET_KEY")

VERCEL_CONFIGURATION_ERRORS = []
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-key"
    else:
        VERCEL_CONFIGURATION_ERRORS.append("Set SECRET_KEY to a unique production value.")

vercel_host = os.environ.get("VERCEL_URL", "").strip()
default_allowed_hosts = "127.0.0.1,localhost,.vercel.app"
if vercel_host:
    default_allowed_hosts = f"{default_allowed_hosts},{vercel_host}"
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", os.environ.get("ALLOWED_HOSTS", default_allowed_hosts))
default_csrf_origins = "https://*.vercel.app"
if vercel_host:
    default_csrf_origins = f"{default_csrf_origins},https://{vercel_host}"
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default_csrf_origins)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'webroaster',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'webroaster.middleware.VercelConfigurationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'webroaster.middleware.PasswordExpiryMiddleware',
    'webroaster.middleware.RequestAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NewCompany.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewCompany.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = first_database_url(
    "DATABASE_URL",
    "POSTGRES_URL",
    "POSTGRES_PRISMA_URL",
    "POSTGRES_URL_NON_POOLING",
    "postgresql",
)

if DATABASE_URL:
    # Hosted production PostgreSQL
    try:
        DATABASES = {
            "default": dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=0,
                conn_health_checks=True,
                ssl_require=database_url_requires_ssl(DATABASE_URL),
            )
        }
    except Exception as exc:
        DATABASES = {"default": fallback_database_config()}
        VERCEL_CONFIGURATION_ERRORS.append(
            "DATABASE_URL is not a valid PostgreSQL URL. Use a full postgres:// or postgresql:// URL and URL-encode special characters in the password."
        )
        if env_bool("DJANGO_STARTUP_DEBUG", False):
            VERCEL_CONFIGURATION_ERRORS.append(f"DATABASE_URL parse error: {exc}")
else:
    # Local development PostgreSQL
    DATABASES = {"default": fallback_database_config()}
    if not DEBUG:
        VERCEL_CONFIGURATION_ERRORS.append(
            "Set DATABASE_URL to a hosted PostgreSQL database, or provide a supported Postgres URL env var."
        )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'NewCompany' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/staff/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
COMPANY_NAME = "NewCompany"

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"

SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", not DEBUG)

SESSION_COOKIE_AGE = int(os.environ.get("DJANGO_SESSION_COOKIE_AGE", "1800"))
SESSION_SAVE_EVERY_REQUEST = True
