from django.urls import path

from webroaster.views.operations import pages
from webroaster.views.operations import views


urlpatterns = [
    path("clients/", views.client_list_create, name="client-list-create"),
    path("clients/<int:pk>/", views.client_detail, name="client-detail"),
    path("sites/", views.site_list_create, name="site-list-create"),
    path("sites/<int:pk>/", views.site_detail, name="site-detail"),
    path("shifts/", views.shift_list_create, name="shift-list-create"),
    path("shifts/<int:pk>/", views.shift_detail, name="shift-detail"),
    path("deployments/", views.deployment_list_create, name="deployment-list-create"),
    path("deployments/<int:pk>/", views.deployment_detail, name="deployment-detail"),
    path("incidents/", views.incident_list_create, name="incident-list-create"),
    path("incidents/<int:pk>/", views.incident_detail, name="incident-detail"),
    path("patrol-logs/", views.patrol_log_list_create, name="patrol-log-list-create"),
    path("patrol-logs/<int:pk>/", views.patrol_log_detail, name="patrol-log-detail"),
    path("assets/", views.asset_list_create, name="asset-list-create"),
    path("assets/<int:pk>/", views.asset_detail, name="asset-detail"),
    path("pages/clients/", pages.client_page_list, name="operations-client-page-list"),
    path("pages/clients/create/", pages.client_page_create, name="operations-client-page-create"),
    path("pages/clients/<int:pk>/", pages.client_page_detail, name="operations-client-page-detail"),
    path("pages/clients/<int:pk>/edit/", pages.client_page_update, name="operations-client-page-update"),
    path("pages/clients/<int:pk>/delete/", pages.client_page_delete, name="operations-client-page-delete"),
    path("pages/sites/", pages.site_page_list, name="operations-site-page-list"),
    path("pages/sites/create/", pages.site_page_create, name="operations-site-page-create"),
    path("pages/sites/<int:pk>/", pages.site_page_detail, name="operations-site-page-detail"),
    path("pages/sites/<int:pk>/edit/", pages.site_page_update, name="operations-site-page-update"),
    path("pages/sites/<int:pk>/delete/", pages.site_page_delete, name="operations-site-page-delete"),
    path("pages/shifts/", pages.shift_page_list, name="operations-shift-page-list"),
    path("pages/shifts/create/", pages.shift_page_create, name="operations-shift-page-create"),
    path("pages/shifts/<int:pk>/", pages.shift_page_detail, name="operations-shift-page-detail"),
    path("pages/shifts/<int:pk>/edit/", pages.shift_page_update, name="operations-shift-page-update"),
    path("pages/shifts/<int:pk>/delete/", pages.shift_page_delete, name="operations-shift-page-delete"),
    path("pages/deployments/", pages.deployment_page_list, name="operations-deployment-page-list"),
    path("pages/deployments/create/", pages.deployment_page_create, name="operations-deployment-page-create"),
    path("pages/deployments/<int:pk>/", pages.deployment_page_detail, name="operations-deployment-page-detail"),
    path("pages/deployments/<int:pk>/edit/", pages.deployment_page_update, name="operations-deployment-page-update"),
    path("pages/deployments/<int:pk>/delete/", pages.deployment_page_delete, name="operations-deployment-page-delete"),
    path("pages/incidents/", pages.incident_page_list, name="operations-incident-page-list"),
    path("pages/incidents/create/", pages.incident_page_create, name="operations-incident-page-create"),
    path("pages/incidents/<int:pk>/", pages.incident_page_detail, name="operations-incident-page-detail"),
    path("pages/incidents/<int:pk>/edit/", pages.incident_page_update, name="operations-incident-page-update"),
    path("pages/incidents/<int:pk>/delete/", pages.incident_page_delete, name="operations-incident-page-delete"),
    path("pages/patrol-logs/", pages.patrol_log_page_list, name="operations-patrol-log-page-list"),
    path("pages/patrol-logs/create/", pages.patrol_log_page_create, name="operations-patrol-log-page-create"),
    path("pages/patrol-logs/<int:pk>/", pages.patrol_log_page_detail, name="operations-patrol-log-page-detail"),
    path("pages/patrol-logs/<int:pk>/edit/", pages.patrol_log_page_update, name="operations-patrol-log-page-update"),
    path("pages/patrol-logs/<int:pk>/delete/", pages.patrol_log_page_delete, name="operations-patrol-log-page-delete"),
    path("pages/assets/", pages.asset_page_list, name="operations-asset-page-list"),
    path("pages/assets/create/", pages.asset_page_create, name="operations-asset-page-create"),
    path("pages/assets/<int:pk>/", pages.asset_page_detail, name="operations-asset-page-detail"),
    path("pages/assets/<int:pk>/edit/", pages.asset_page_update, name="operations-asset-page-update"),
    path("pages/assets/<int:pk>/delete/", pages.asset_page_delete, name="operations-asset-page-delete"),
]

