from django.urls import path

from webroaster.views.finance import pages
from webroaster.views.finance import views


urlpatterns = [
    path("salaries/", views.salary_list_create, name="salary-list-create"),
    path("salaries/<int:pk>/", views.salary_detail, name="salary-detail"),
    path("advances/", views.advance_list_create, name="advance-list-create"),
    path("advances/<int:pk>/", views.advance_detail, name="advance-detail"),
    path("invoices/", views.invoice_list_create, name="invoice-list-create"),
    path("invoices/<int:pk>/", views.invoice_detail, name="invoice-detail"),
    path("payments/", views.payment_list_create, name="payment-list-create"),
    path("payments/<int:pk>/", views.payment_detail, name="payment-detail"),
    path("payrolls/", views.payroll_list_create, name="payroll-list-create"),
    path("payrolls/<int:pk>/", views.payroll_detail, name="payroll-detail"),
    path("budgets/", views.budget_list_create, name="budget-list-create"),
    path("budgets/<int:pk>/", views.budget_detail, name="budget-detail"),
    path("expenses/", views.expense_list_create, name="expense-list-create"),
    path("expenses/<int:pk>/", views.expense_detail, name="expense-detail"),
    path("pages/salaries/", pages.salary_page_list, name="finance-salary-page-list"),
    path("pages/salaries/create/", pages.salary_page_create, name="finance-salary-page-create"),
    path("pages/salaries/<int:pk>/", pages.salary_page_detail, name="finance-salary-page-detail"),
    path("pages/salaries/<int:pk>/edit/", pages.salary_page_update, name="finance-salary-page-update"),
    path("pages/salaries/<int:pk>/delete/", pages.salary_page_delete, name="finance-salary-page-delete"),
    path("pages/advances/", pages.advance_page_list, name="finance-advance-page-list"),
    path("pages/advances/create/", pages.advance_page_create, name="finance-advance-page-create"),
    path("pages/advances/<int:pk>/", pages.advance_page_detail, name="finance-advance-page-detail"),
    path("pages/advances/<int:pk>/edit/", pages.advance_page_update, name="finance-advance-page-update"),
    path("pages/advances/<int:pk>/delete/", pages.advance_page_delete, name="finance-advance-page-delete"),
    path("pages/invoices/", pages.invoice_page_list, name="finance-invoice-page-list"),
    path("pages/invoices/create/", pages.invoice_page_create, name="finance-invoice-page-create"),
    path("pages/invoices/<int:pk>/", pages.invoice_page_detail, name="finance-invoice-page-detail"),
    path("pages/invoices/<int:pk>/edit/", pages.invoice_page_update, name="finance-invoice-page-update"),
    path("pages/invoices/<int:pk>/delete/", pages.invoice_page_delete, name="finance-invoice-page-delete"),
    path("pages/payments/", pages.payment_page_list, name="finance-payment-page-list"),
    path("pages/payments/create/", pages.payment_page_create, name="finance-payment-page-create"),
    path("pages/payments/<int:pk>/", pages.payment_page_detail, name="finance-payment-page-detail"),
    path("pages/payments/<int:pk>/edit/", pages.payment_page_update, name="finance-payment-page-update"),
    path("pages/payments/<int:pk>/delete/", pages.payment_page_delete, name="finance-payment-page-delete"),
    path("pages/payrolls/", pages.payroll_page_list, name="finance-payroll-page-list"),
    path("pages/payrolls/create/", pages.payroll_page_create, name="finance-payroll-page-create"),
    path("pages/payrolls/<int:pk>/", pages.payroll_page_detail, name="finance-payroll-page-detail"),
    path("pages/payrolls/<int:pk>/edit/", pages.payroll_page_update, name="finance-payroll-page-update"),
    path("pages/payrolls/<int:pk>/delete/", pages.payroll_page_delete, name="finance-payroll-page-delete"),
    path("pages/budgets/", pages.budget_page_list, name="finance-budget-page-list"),
    path("pages/budgets/create/", pages.budget_page_create, name="finance-budget-page-create"),
    path("pages/budgets/<int:pk>/", pages.budget_page_detail, name="finance-budget-page-detail"),
    path("pages/budgets/<int:pk>/edit/", pages.budget_page_update, name="finance-budget-page-update"),
    path("pages/budgets/<int:pk>/delete/", pages.budget_page_delete, name="finance-budget-page-delete"),
    path("pages/expenses/", pages.expense_page_list, name="finance-expense-page-list"),
    path("pages/expenses/create/", pages.expense_page_create, name="finance-expense-page-create"),
    path("pages/expenses/<int:pk>/", pages.expense_page_detail, name="finance-expense-page-detail"),
    path("pages/expenses/<int:pk>/edit/", pages.expense_page_update, name="finance-expense-page-update"),
    path("pages/expenses/<int:pk>/delete/", pages.expense_page_delete, name="finance-expense-page-delete"),
]

